packages:
  - internal
  - config
  - comark
  - query
  - components
  - composables
  - theme
  - locale
  - shared
  - entry
  - vike
  - app
  - docs
allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  esbuild: true
  sharp: true
  vue-demi: true
minimumReleaseAgeExclude:
  - vike
  - '@vue/compiler-core'
  - '@vue/compiler-dom'
  - '@vue/compiler-sfc'
  - '@vue/compiler-ssr'
  - '@vue/reactivity'
  - '@vue/runtime-core'
  - '@vue/runtime-dom'
  - '@vue/server-renderer'
  - '@vue/shared'
  - vue
